[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# React Router fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
